analyzer:
  errors:
    constant_identifier_names: ignore
    non_constant_identifier_names: ignore
    strict_top_level_inference: ignore
include: package:flutter_lints/flutter.yaml
linter:
  rules:
    
